import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import 'leaflet/dist/leaflet.css';
import Header from './Home/Header/header';
import { Providers } from './providers'; // Importamos

const roboto = Roboto({
  variable: '--font-roboto',
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Servineo',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.variable} antialiased`}>
        <Providers> {/* Envolvemos la app con los Providers */}
          <Header />
          <main className="pb-20 lg:pb-0">{children}</main>
        </Providers>
      </body>
    </html>
  );
}